application: pipeline-test
version: 1
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /_pipeline(/.*)?
  script: pipeline.handlers._APP

- url: /static
  static_dir: static

- url: .*
  login: required
  script: main.APP
