// Copyright 2011 Google Inc.
// 
// Licensed under the Apache License, Version 2.0 (the "License"); you may not
// use this file except in compliance with the License. You may obtain a copy of
// the License at
// 
// http://www.apache.org/licenses/LICENSE-2.0
// 
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
// WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
// License for the specific language governing permissions and limitations under
// the License.

package com.google.appengine.tools.pipeline;

/**
 * An Exception that indicates that the object with the specified key has been
 * orphaned. Orphaned objects may be generated by the Pipeline framework if an
 * error occurs during the running of a job. The orphaned objects will be safely
 * cleaned up when the Pipeline is deleted, but they will not take part in
 * any Pipeline processing and should not be used.
 * 
 * @author rudominer@google.com (Mitch Rudominer)
 */
public class NoSuchObjectException extends Exception {
  private static final long serialVersionUID = 949320101929454628L;

  public NoSuchObjectException(String key) {
    super(key);
  }

  public NoSuchObjectException(String key, Throwable cause) {
    super(key, cause);
  }
}
